### ISSUE TITLE
Linear Algebra - Learning from Data Book

### ISSUE THREAD

**Issue by ysnreddy** [gagan-iitb/CS550#22]
Linear Algebra - Learning from Data by Gilbert Strang
[Gilbert Strang - Linear Algebra and Learning from Data-Wellesley-Cambridge Press (2019)_compressed.pdf](https://github.com/gagan-iitb/CS550/files/12445454/Gilbert.Strang.-.Linear.Algebra.and.Learning.from.Data-Wellesley-Cambridge.Press.2019._compressed.pdf)

**Comment by gagan-iitb** [comment]
Thanks for the link
